Fix errors in php 8.0 (tested ingame)
JaxkDev/Bounty pull request #24
Opened 2021-08-04 13:18 UTC by JoshuaPHYT

2021-08-04 23:32 UTC, Lycol50 requested changes

2021-08-04 23:32 UTC, Lycol50 commented on src/Jack/Bounty/EventListener.php
> +                        $msg = str_replace('{SENDER}', $sender->getName(), str_replace('{AMOUNT}', "$amount",str_replace('{PLAYER}',$noob->getName(),$this->colour($this->plugin->config["bounty_new_br
variables are not strings

2021-08-04 23:32 UTC, Lycol50 commented on src/Jack/Bounty/EventListener.php
> +                        $msg = str_replace("{MAX}", "$max", str_replace("{MIN}", "$min", $this->colour($this->plugin->config["bounty_new_fundlimit"])));
variables are not strings

2021-08-05 06:15 UTC, JaxkDev commented on src/Jack/Bounty/EventListener.php
> +                        $msg = str_replace('{SENDER}', $sender->getName(), str_replace('{AMOUNT}', "$amount",str_replace('{PLAYER}',$noob->getName(),$this->colour($this->plugin->config["bounty_new_br
What ?
This is valid syntax.

2021-08-05 06:17 UTC, JaxkDev commented
Please re target branch to development.
Also please be consistent with casting here, you’ve used 3 different styles, “$var”, (string)$var and (string)($var) please stick with one through preferably strval()

2022-05-08 05:49 UTC, JaxkDev commented
Inactive.

2022-05-08 05:49 UTC, closed without merging